sudo: required
dist: bionic

branches:
  only:
    - master

language: minimal

notifications:
  email: false
  slack:
    secure: iKe1UVHgKeUgYATFivkl6oKJo2SRFyVeIITBG3mBq7PZvJ2KtZeML/vVLZVd0dqWiIAT6IEKMdaGROfqhh786VRRQ0UJp6Ie5/Lyhz4Ixd7lULaBVLzyC3o+RGaimpjwjIx73XshEsz8NFbkWTm1zpX6rTDiTCUC2GqhjwGhU/89veVymTDs4DA4sfopVtSMr2wL32LiDq9FIF6/iCCmlrdoil8FLVtLcQBGORpmHD5RM4DOXfmR5fHdIE0NUJksXE/0RQbNYFD1jx5jhvCNURVBX74AqQjoQ8M2w+31HGzjz+J503fGZeIcPXveTyGXOf+1uZRMMOcgSC8isLqB4+aYh2TRlCeqDVocLAkVp+M1bXEAx6AIJ9JRTKET5GPTkc2iN+YQ/XcBbyKQtQTru/0LQ/IWNbE6sKzla3jD07J2vuV5+9+Llim38yxXv4o5gzd+kx9xRwuTabNPtSxHnlpzJzJw6klvk6sNthtVe04sN/pLs6omH5YYaQOCI8rb20YG6Gv7lyuHC+ugxUoVW7uvyVMVuR6dtwd2Aa1mBFqWhIh2ShCdD2Q8R/ZjwOp5UDiGCpWl1Gfm83KmKmA4oe0/oUL02R7tXVHmtRvEpvPAHkgEbX3DGVJpRw4YdoDNogOuyKfWYt9ZxDiVObb1mLgxBfzk7N31J74QRgnGA7I=

services:
  - docker
before_install:
  - sudo ./vm-setup.sh
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    fi

jobs:
  include:
    - stage: build-and-push-tcpreplay+rustils
      name: tcpreplay
      script: |
              make -f docker.mk build-tcpreplay || travis_terminate 1
              if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                make -f docker.mk push-tcpreplay || travis_terminate 1
              fi
    - name: build-and-push-rustils
      script: |
              make -f docker.mk build-rustils || travis_terminate 1
              if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                make -f docker.mk push-rustils || travis_terminate 1
              fi
    - stage: build-and-push-dpdk
      name: dpdk
      script: |
              make -f docker.mk build-dpdk
              if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                make -f docker.mk push-dpdk || travis_terminate 1
              fi
    - stage: build-and-push-containers
    - name: dpdk-devbind
      script: |
              make -f docker.mk build-dpdk-devbind || travis_terminate 1
              if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                make -f docker.mk push-dpdk-devbind || travis_terminate 1
              fi
    - name: sandbox
      script: |
              make -f docker.mk build-sandbox || travis_terminate 1
              if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                make -f docker.mk push-sandbox || travis_terminate 1
              fi
    - name: dind
      script: |
              make -f docker.mk build-dind || travis_terminate 1
              if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                make -f docker.mk push-dind || travis_terminate 1
              fi
    - name: esm
      script: |
              make -f docker.mk build-esm || travis_terminate 1
              if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                make -f docker.mk push-esm || travis_terminate 1
              fi
    - name: gobgp
      script: |
              make -f docker.mk build-gobgp || travis_terminate 1
              if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                make -f docker.mk push-gobgp || travis_terminate 1
              fi
    - name: packer-ansible
      script: |
              make -f docker.mk build-packer-ansible || travis_terminate 1
              if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                make -f docker.mk push-packer-ansible || travis_terminate 1
              fi
